name: bittorrent-tracker-editor
adopt-info: mainprogram
icon: metainfo/io.github.gerryferdinandus.bittorrent-tracker-editor.png

base: core22
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  bittorrent-tracker-editor:
    desktop: mainprogram/io.github.gerryferdinandus.bittorrent-tracker-editor.desktop
    extensions:
      - kde-neon
    command: mainprogram/trackereditor
    environment:
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
    plugs:
      - home
      - network
      - removable-media
      - pulseaudio

parts:
  mainprogram: # Build and add to snap the main program: mainprogram/trackereditor
    source: https://github.com/GerryFerdinandus/bittorrent-tracker-editor.git
    parse-info: [metainfo/io.github.gerryferdinandus.bittorrent-tracker-editor.metainfo.xml]
    plugin: nil
    override-build: |
      craftctl default
      lazbuild --build-mode=Release --widgetset=qt5 source/project/tracker_editor/trackereditor.lpi
      mkdir $CRAFT_PART_INSTALL/mainprogram
      cp enduser/trackereditor $CRAFT_PART_INSTALL/mainprogram
      cp metainfo/io.github.gerryferdinandus.bittorrent-tracker-editor.desktop $CRAFT_PART_INSTALL/mainprogram
    build-packages:
      - fpc
      - lazarus
      - libqt5pas-dev

  libQt5Pas: # Add to snap the libQt5Pas support library : usr/lib/*/libQt5Pas.*
    plugin: nil
    stage-packages:
      - libqt5pas1
    prime:
      - usr/lib/*/libQt5Pas.*

# Only 3 files are explicitly added in this snap:
# trackereditor + .desktop file via copy command
# libQt5Pas.so via prime
#
# Use: 'unsquashfs *.snap' to look what is inside the snap file.
