name: CI/CD with Lazarus IDE on multiple operating systems.

permissions:
  contents: write

on:
    push:
    pull_request:
    workflow_dispatch:
    # Automatic cron build every 6 months to check if everything still works.
    schedule:
    - cron: "0 0 1 1/6 *"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      # Set up an array to perform the following three build configurations.
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            LAZBUILD_WITH_PATH: c:/lazarus/lazbuild
            RELEASE_ZIP_FILE: trackereditor_windows_amd64.zip
            LAZ_OPT:
          - os: ubuntu-latest
            LAZBUILD_WITH_PATH: lazbuild
            RELEASE_ZIP_FILE: trackereditor_linux_amd64_gtk2.zip
            LAZ_OPT: --widgetset=gtk2
          - os: macos-latest
            LAZBUILD_WITH_PATH: /Applications/Lazarus/lazbuild
            RELEASE_ZIP_FILE: trackereditor_macOS_amd64.zip
            LAZ_OPT: --widgetset=cocoa

    steps:
    - uses: actions/checkout@v4

    - name: Install Lazarus IDE
      run:   |
           if [ "$RUNNER_OS" == "Linux" ]; then
                sudo apt install -y lazarus zip xvfb
           elif [ "$RUNNER_OS" == "Windows" ]; then
                choco install lazarus zip
                # https://wiki.overbyte.eu/wiki/index.php/ICS_Download#Download_OpenSSL_Binaries
                curl -L -O --output-dir enduser https://github.com/GerryFerdinandus/bittorrent-tracker-editor/releases/download/V1.32.0/libssl-3-x64.dll
                curl -L -O --output-dir enduser https://github.com/GerryFerdinandus/bittorrent-tracker-editor/releases/download/V1.32.0/libcrypto-3-x64.dll
           elif [ "$RUNNER_OS" == "macOS" ]; then
                brew install --cask lazarus
           else
                echo "$RUNNER_OS not supported"
                exit 1
           fi
      shell: bash

    - name: Build Release version
      # Build trackereditor project (Release mode)
      run: ${{ matrix.LAZBUILD_WITH_PATH }} --build-all --build-mode=Release ${{ matrix.LAZ_OPT }} source/project/tracker_editor/trackereditor.lpi
      shell: bash

    - name: Build Unit Test on Windows
      if: matrix.os == 'windows-latest'
      # Build unit test project (Debug mode)
      run: ${{ matrix.LAZBUILD_WITH_PATH }} --build-all --build-mode=Debug ${{ matrix.LAZ_OPT }} source/project/unit_test/tracker_editor_test.lpi
      shell: bash

    - name: Run Unit Test on Windows
      if: matrix.os == 'windows-latest'
      # Also remove all the extra file created by test.
      # We do not what it in the ZIP release files.
      # Undo all changes made by testing.
      run:  |
        set -e
        enduser/test_trackereditor -a --format=plain
        set +e

        # remove file created by unit test
        rm -f enduser/console_log.txt
        rm -f enduser/export_trackers.txt
        git reset --hard
      shell: bash

    - name: Test OpenSSL works on Linux CI
      if: matrix.os == 'ubuntu-latest'
      run: xvfb-run --auto-servernum enduser/trackereditor -TEST_SSL

    - name: Create a zip file for Linux release.
      if: matrix.os == 'ubuntu-latest'
      run: zip -j ${{ matrix.RELEASE_ZIP_FILE }} enduser/*.txt enduser/trackereditor
      shell: bash

    - name: Create a zip file for Windows release.
      if: matrix.os == 'windows-latest'
      run: |
        zip -j ${{ matrix.RELEASE_ZIP_FILE }} enduser/*.txt enduser/trackereditor.exe enduser/*.dll
      shell: bash

    - name: Move program and icon into macOS .app
      if: matrix.os == 'macos-latest'
      env:
        ICON_FILE: 'metainfo/io.github.gerryferdinandus.bittorrent-tracker-editor.png'
        PROGRAM_NAME_WITH_PATH: 'enduser/trackereditor'
      run: |
        # remove the path
        PROGRAM_NAME_ONLY=$(basename -- "$PROGRAM_NAME_WITH_PATH")

        # ------ Move program to app
        # remove symbolic link in app. Need real program here.
        rm -f "${PROGRAM_NAME_WITH_PATH}.app/Contents/MacOS/${PROGRAM_NAME_ONLY}"
        # copy the program to the app version.
        mv -f "${PROGRAM_NAME_WITH_PATH}" "${PROGRAM_NAME_WITH_PATH}.app/Contents/MacOS"

        # ------ Create icon set and move it into the app
        iconset_folder="temp_folder.iconset"
        rm -rf "${iconset_folder}"
        mkdir -p "${iconset_folder}"

        for s in 16 32 128 256 512; do
          d=$(($s*2))
          sips -Z $s $ICON_FILE --out "${iconset_folder}/icon_${s}x$s.png"
          sips -Z $d $ICON_FILE --out "${iconset_folder}/icon_${s}x$s@2x.png"
        done

        # create .icns icon file
        iconutil -c icns "${iconset_folder}" -o "iconfile.icns"
        rm -r "${iconset_folder}"

        # move icon file to the app
        mv -f "iconfile.icns"  "${PROGRAM_NAME_WITH_PATH}.app/Contents/Resources"

        # add icon to plist xml file CFBundleIconFile = "iconfile"
        plutil -insert CFBundleIconFile -string "iconfile" "${PROGRAM_NAME_WITH_PATH}.app/Contents/Info.plist"
      shell: bash

    - name: Codesign macOS app bundle
      # This macOS Codesign step is copied from:
      # https://federicoterzi.com/blog/automatic-code-signing-and-notarization-for-macos-apps-using-github-actions/
      # This is a bit different from the previous version for Travis-CI build system to build bittorrent tracker editor
      if: matrix.os == 'macos-latest'
      env:
        MACOS_CERTIFICATE: ${{ secrets.PROD_MACOS_CERTIFICATE }}
        MACOS_CERTIFICATE_PWD: ${{ secrets.PROD_MACOS_CERTIFICATE_PWD }}
        MACOS_CERTIFICATE_NAME: ${{ secrets.PROD_MACOS_CERTIFICATE_NAME }}
        MACOS_CI_KEYCHAIN_PWD: ${{ secrets.PROD_MACOS_CI_KEYCHAIN_PWD }}
        MACOS_APP: enduser/trackereditor.app
      run: |
        # Turn our base64-encoded certificate back to a regular .p12 file
        echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12

        # We need to create a new keychain, otherwise using the certificate will prompt
        # with a UI dialog asking for the certificate password, which we can't
        # use in a headless CI environment

        security create-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
        security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$MACOS_CI_KEYCHAIN_PWD" build.keychain

        # We finally codesign our app bundle, specifying the Hardened runtime option.
        #/usr/bin/codesign --force -s "$MACOS_CERTIFICATE_NAME" --options runtime "$MACOS_APP" -v

        # sign the app. -sign is the developer cetificate ID
        # Must use --deep to sign all internal content
        /usr/bin/codesign --timestamp --force --options runtime --deep --sign "$MACOS_CERTIFICATE_NAME" "$MACOS_APP"
      shell: bash

    - name: Notarize macOS app bundle
      if: matrix.os == 'macos-latest'
      env:
        PROD_MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_APPLE_ID }}
        PROD_MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_TEAM_ID }}
        PROD_MACOS_NOTARIZATION_PWD: ${{ secrets.PROD_MACOS_NOTARIZATION_PWD }}
        MACOS_APP: enduser/trackereditor.app
      run: |
        # Store the notarization credentials so that we can prevent a UI password dialog
        # from blocking the CI

        echo "Create keychain profile"
        xcrun notarytool store-credentials "notarytool-profile" --apple-id "$PROD_MACOS_NOTARIZATION_APPLE_ID" --team-id "$PROD_MACOS_NOTARIZATION_TEAM_ID" --password "$PROD_MACOS_NOTARIZATION_PWD"

        # We can't notarize an app bundle directly, but we need to compress it as an archive.
        # Therefore, we create a zip file containing our app bundle, so that we can send it to the
        # notarization service

        echo "Creating temp notarization archive"
        ditto -c -k --keepParent "$MACOS_APP" "notarization.zip"

        # Here we send the notarization request to the Apple's Notarization service, waiting for the result.
        # This typically takes a few seconds inside a CI environment, but it might take more depending on the App
        # characteristics. Visit the Notarization docs for more information and strategies on how to optimize it if
        # you're curious

        echo "Notarize app"
        xcrun notarytool submit "notarization.zip" --keychain-profile "notarytool-profile" --wait

        # Finally, we need to "attach the staple" to our executable, which will allow our app to be
        # validated by macOS even when an internet connection is not available.
        echo "Attach staple"
        xcrun stapler staple "$MACOS_APP"

        # Remove notarization.zip, otherwise it will also be 'released' to the end user
        rm -f "notarization.zip"

        # zip only the app folder.
        echo "Zip macOS app file"
        /usr/bin/ditto -c -k --keepParent "$MACOS_APP" "${{ matrix.RELEASE_ZIP_FILE }}"
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact-${{ matrix.os }}
        path: ${{ matrix.RELEASE_ZIP_FILE }}
        compression-level: 0 # no compression. Content is already a zip file
        if-no-files-found: error

    - name: Zip file release to end user
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          *.zip
